### ISSUE TITLE
Error running example

### ISSUE THREAD

**Issue by josb86** [Dobot-Arm/TCP-IP-Protocol#7]
Hi I am trying run the example code whirta a MG400 robot, a I get this error ('Unable to set socket connection use port 30004 !', <class 'OSError'>). How I can fix this?.

**Comment by nazpiroz** [comment]
Try port 30005

**Comment by josb86** [comment]
Traceback (most recent call last):
  File "d:/Documentos/Proyectos Python/TCP-IP-4Axis-Python-CMD-main_original/main.py", line 69, in <module>      
    dashboard, move, feed = connect_robot()
  File "d:/Documentos/Proyectos Python/TCP-IP-4Axis-Python-CMD-main_original/main.py", line 27, in connect_robot 
    raise e
  File "d:/Documentos/Proyectos Python/TCP-IP-4Axis-Python-CMD-main_original/main.py", line 20, in connect_robot 
    feed = DobotApi(ip, feed_p)
  File "d:\Documentos\Proyectos Python\TCP-IP-4Axis-Python-CMD-main_original\dobot_api.py", line 134, in __init__
    raise Exception(
Exception: Connect to dashboard server need use port 30005 !
